[package]
name = "fontconfig_sys"
version = "0.0.1"
authors = ["Lukas Fürmetz <fuermetz@mailbox.org>"]
keywords = ["fontconfig", "fc", "font"]
description = "Low level bindings to fontconfig."
build = "build.rs"

[dependencies]
libc = "0.1.10"

[build-dependencies]
pkg-config = "0.3.5"
